services:

  db:
    # Build
    image: mariadb:${MARIADB_VERSION:-latest}
    # Deploy
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT:-3306}:3306

  importer:
    # Build
    build:
      context: ./mariadb
      target: importer
    # Deploy
    depends_on:
      db:
        condition: service_healthy
        restart: false
    environment:
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-db}
    volumes:
      - ./mariadb/data:/app/data
