# Services definition for building & deploying

services:

  db:
    # Extend
    extends:
      file: ./postgres/docker-compose.yml
      service: db

  importer:
    # Extend
    extends:
      file: ./postgres/docker-compose.yml
      service: importer
    # Deploy
    depends_on:
      db:
        condition: service_healthy
        restart: true
