version: '3.8'
services:

  db:
    # Build
    image: mariadb:${MARIADB_VERSION:-latest}
    # Deploy
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
    - "${DB_PORT:-3306}:3306"
